Building the business services 
==============================

Learn how to design and implement the business layer of an application and how to make it usable by various front-ends
----------------------------------------------------------------------------------------------------------------------

You've just defined the domain model of your application and created its persistence layer. Now you need to implement the services that implement the business logic of your application and expose them to the front-end. After reading this, you'll understand how to design the business layer and what choices to make while developing it. Topics covered include:

* Implementing basic persistence operations (?)
* Encapsulating business logic in services and integrating with the persistence tier
* Using CDI for integrating individual services
* Integration testing using Arquillian
* Implementing cross-cutting concerns such as logging
* Exposing RESTful services via JAX-RS

The tutorial will show you how to perform all these steps in JBoss Developer Studio, including screenshots that guide you through. For those of you who prefer to watch and learn, the included video shows you how we performed all the steps.
